services:
  - type: web
    name: wb-lima-api
    runtime: python3
    plan: free
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11
